version: 2.1
executors:
  js-env:
    docker:
      - image: circleci/node:16.6.0

jobs:
  js-test:
    executor: js-env
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run:
          name: Install package
          command: npm ci
      - save_cache:
          paths:
            - node_modules
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: 
          name: Execute test
          command: npm run test:unit
  deploy:
    executor: js-env
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run:
          name: Install package
          command: npm ci
      - run:
          name: Build
          command: npm run build
      - add_ssh_keys:
          fingerprints: 
            - "${FINGERPRINT}"
      - run:
          name: Deploy
          command: scp -oStrictHostKeyChecking=no -r dist/* "${USER_NAME}@${HOST_NAME}:${APP_DIR}"


workflows:
  version: 2.1
  js:
    jobs:
      - js-test:
          filters:
            branches:
              ignore: master
      - deploy:
          filters:
            branches:
              only: master